-- Create Department Table
CREATE TABLE Department (
 DepartmentID INT PRIMARY KEY,
 DepartmentName VARCHAR(100) NOT NULL UNIQUE
);

-- Create Designation Table
CREATE TABLE Designation (
 DesignationID INT PRIMARY KEY,
 DesignationName VARCHAR(100) NOT NULL UNIQUE
);

-- Create Person Table
CREATE TABLE Person (
 PersonID INT PRIMARY KEY IDENTITY(101,1),
 FirstName VARCHAR(100) NOT NULL,
 LastName VARCHAR(100) NOT NULL,
 Salary DECIMAL(8, 2) NOT NULL,
 JoiningDate DATETIME NOT NULL,
 DepartmentID INT NULL,
 DesignationID INT NULL,
 FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID),
 FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID)
);

--LAB2 PART A

--1.INSERTDEPDATA
CREATE OR ALTER PROCEDURE PR_INSDEPDATA
@DID INT,
@DNAME VARCHAR(50)
AS
BEGIN
	INSERT INTO Department VALUES (@DID , @DNAME);
END

EXEC PR_INSDEPDATA 1,'ADMIN';
EXEC PR_INSDEPDATA 2,'IT';
EXEC PR_INSDEPDATA 3,'HR';
EXEC PR_INSDEPDATA 4,'ACCOUNT';

SELECT * FROM Department;
DELETE FROM Department;

--1.UPDATEDEPDATA
CREATE OR ALTER PROCEDURE PR_UPDEPDATA
@DID INT,
@DNAME VARCHAR(50)
AS
BEGIN
	UPDATE DEPARTMENT
	SET DepartmentName = @DNAME
	WHERE DepartmentID = @DID
END

EXEC PR_UPDEPDATA 1 , 'VALUE';

--1.DELETEDEPDATA
CREATE OR ALTER PROCEDURE PR_DELDEPDATA
@DID INT
AS
BEGIN
	DELETE  FROM DEPARTMENT
	WHERE DepartmentID = @DID
END

EXEC PR_DELDEPDATA 4; 

--1.INSERTDESIDATA
CREATE OR ALTER PROCEDURE PR_INSDESDATA
@DESID INT,
@DESINAME VARCHAR(50)
AS
BEGIN
	INSERT INTO Designation VALUES (@DESID , @DESINAME);
END

EXEC PR_INSDESDATA 11 , 'JOBBER';
EXEC PR_INSDESDATA 12 , 'WELDER';
EXEC PR_INSDESDATA 13 , 'CLERK';
EXEC PR_INSDESDATA 14 , 'MANAGER';
EXEC PR_INSDESDATA 15 , 'CEO';

--1.UPDATEDESIDATA
CREATE OR ALTER PROCEDURE PR_UPDESIPDATA
@DESID INT,
@DESINAME VARCHAR(50)
AS
BEGIN
	UPDATE Designation
	SET DesignationName = @DESINAME
	WHERE DesignationID = @DESID
END

--1.DELETEDESIPDATA
CREATE OR ALTER PROCEDURE PR_DELDESIDATA
@DESID INT
AS
BEGIN
	DELETE  FROM Designation
	WHERE DesignationID = @DESID
END

SELECT * FROM Designation;

--1.INSERTPERDATA
CREATE OR ALTER PROCEDURE PR_INSPERDATA
@FNAME VARCHAR(50),
@LNAME VARCHAR(50),
@SAL INT,
@JD DATETIME,
@DID INT,
@DESID INT 
AS
BEGIN
	INSERT INTO Person VALUES (@FNAME , @LNAME , @SAL , @JD , @DID , @DESID);
END

--DROP TABLE Person;

SELECT * FROM Person;
EXEC PR_INSPERDATA 'RAHUL' , 'ANSHU' , 56000 , '1990-01-01' , 1 , 12;
EXEC PR_INSPERDATA 'HARDIK' , 'HINSU' , 18000 , '1990-09-25' , 2 , 11;
EXEC PR_INSPERDATA 'BHAVIN' , 'KAMANI' , 25000 , '1991-05-14' , NULL , 11;
EXEC PR_INSPERDATA 'BHOOMI' , 'PATEL' , 39000 , '2014-02-20' , 1 , 13;
EXEC PR_INSPERDATA 'ROHIT' , 'RAJGOR' , 17000 , '1990-07-23' , 2 , 15;
EXEC PR_INSPERDATA 'PRIYA' , 'MEHTA' , 250000, '1990-10-18' , 2 , NULL;
EXEC PR_INSPERDATA 'NEHA' , 'TRIVEDI' , 18000 , '2014-02-20' , 3 , 15;